name: Vercel Preview URL Lighthouse Audit
on: [push]

jobs:
  lighthouse_audit:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to PR
        id: loading_comment_to_pr
        uses: marocchino/sticky-pull-request-comment@v2.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          number: ${{ github.event.issue.number }}
          header: lighthouse
          message: |
            Running Lighthouse audit... 
      - name: Capturevercel-preview-url
        id: vercel_preview_url
        uses: zentered/vercel-preview-url@v1.0.0
        env:  
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} 

      - name: Audit preview URL with Lighthouse
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@v9
        with:
          github-token: ${{secrets.LHCI_GITHUB_APP_TOKEN }}
          urls: |
            ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
          uploadArtifacts: true
          temporaryPublicStorage: true

